# Simple workflow for deploying static content to GitHub Pages
name: CI CD for GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']
    # Não leva em conta mudanças na pasta android, que é onde fica o código do app mobile
    paths-ignore:
      - 'android/**'
  pull_request:
    branches: ['master']
    paths-ignore:
      - 'android/**'

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Run tests on pull requests
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Test Node.js lts/*
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
  # Deploy to GitHub Pages only on push to master
  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Define um diretório de trabalho padrão para os comandos `run`
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5